# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
arrayNumpy = np.array([28, 97, 12, 397, 2])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
arraySorted= np.sort(arrayNumpy)
print(arraySorted)

[  2  12  28  97 397]


# Problem 2

In [5]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
arrayNumpy1=([10,15,30,45,60])
print(f"1- (10,15,30,45,60) değerlerine sahip numpy dizisi: {arrayNumpy1}\n")

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arrayNumpy2 =np.arange (5,16)
print(f"2- (5-15) arasındaki sayılarla numpy dizisi: {arrayNumpy2}\n")
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arrayNumpy3 = np.arange (50,101,5)
print(f"3- (50-100) arasında 5'er 5'er artarak numpy dizisi: {arrayNumpy3}\n")

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arrayNumpy4= np.full(10,0)
print(f"4- 10 elemanlı sıfırlardan oluşan bir dizi: {arrayNumpy4}\n")

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arrayNumpy5=np.full(10,1)
print(f"5- 10 elemanlı birlerden oluşan bir dizi: {arrayNumpy5}\n")

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arrayNumpy6= np.linspace(0,100,5)
print(f"6- (0-100) arasında eşit aralıklı 5 sayı: {arrayNumpy6}\n")

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arrayNumpy7= np.random.randint(10,31,size=5)
print(f"7- (10-30) arasında rastgele 5 tane tamsayı:{arrayNumpy7}\n")

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arrayNumpy8= np.random.uniform(-1,1,size=10)
print(f"8- [-1 ile 1] arasında 10 adet sayı: {arrayNumpy8}\n")

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrixNumpy1 = np.random.randint(10,51, size=(3,5))
print(f"9- (3x5) boyutlarında (10-50) arasında rastgele bir matris:\n {matrixNumpy1}\n")

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
matrixNumpy1RowSum= matrixNumpy1.sum(axis=1)
matrixNumpy1ColSum= matrixNumpy1.sum(axis=0)
print(f"10- Matris'in sütun sayıları toplamı:{matrixNumpy1ColSum}\n")
print(f"10- Matris'in satır sayıları toplamı:{matrixNumpy1RowSum}\n")

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
matrixNumpy1max=np.max(matrixNumpy1)
print(f"11- Matrisin en büyük değeri: {matrixNumpy1max}")

matrixNumpy1min=np.min(matrixNumpy1)
print(f"11- Matrisin en küçük değeri: {matrixNumpy1min}")

matrixNumpy1mean=np.mean(matrixNumpy1)
print(f"11- Matrisin ortalama değeri: {matrixNumpy1mean}\n")

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
matrixNumpy1maxIndex=np.argmax(matrixNumpy1)
print(f"12- Matrisin en büyük değerinin indeksi: {matrixNumpy1maxIndex}\n")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arrayNumpy9=np.random.randint(10,21, size=10)
print(f"13- (10-20) arasındaki sayıları içeren dizi:{arrayNumpy9}")

arrayNumpy9three= arrayNumpy9[:3]
print(f"13- İlk 3 elemanı:{arrayNumpy9three}\n")

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
arrayNumpy9reversed= arrayNumpy9[::-1]
print(f"14- Üretilen dizinin elemanlarının tersten yazılışı: {arrayNumpy9reversed}\n")

# 15- Üretilen matrisin ilk satırını seçiniz.
matrixNumpy1firstRow= matrixNumpy1[0, :]
print(f"15- Matris:\n {matrixNumpy1}")
print(f"15- Üretilen matrisin ilk satırı: {matrixNumpy1firstRow}\n")

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(f"16- Matris:\n {matrixNumpy1}")

#indexler 0 dan başladığı için
matrixNumpy1row2col3= matrixNumpy1[1,2]
print(f"16- Üretilen matrisin 2.satır 3.sütundaki elemanı: {matrixNumpy1row2col3}\n")

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(f"17- Matris:\n {matrixNumpy1}")
matrixNumpy1firstCol= matrixNumpy1[:,0]
print(f"17- Üretilen matrisin tüm satırlardaki ilk elemanı: {matrixNumpy1firstCol}\n")

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(f"18- Matris:\n {matrixNumpy1}\n")
matrixNumpy1power= np.power(matrixNumpy1,2)
print(f"18- Üretilen matrisin her bir elemanının karesi:\n {matrixNumpy1power}\n")

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrixNumpy2 = np.random.randint(-50, 51, size=(3, 5))
print("19- Matris:\n", matrixNumpy2)

matrixNumpy2positive= []

for row in matrixNumpy2:
    for num in row:
        if num > 0 and num % 2 == 0:
            matrixNumpy2positive.append(num)
print(f"19- Üretilen matris elemanlarının hangisi pozitif çift sayılar: {matrixNumpy2positive}")

1- (10,15,30,45,60) değerlerine sahip numpy dizisi: [10, 15, 30, 45, 60]

2- (5-15) arasındaki sayılarla numpy dizisi: [ 5  6  7  8  9 10 11 12 13 14 15]

3- (50-100) arasında 5'er 5'er artarak numpy dizisi: [ 50  55  60  65  70  75  80  85  90  95 100]

4- 10 elemanlı sıfırlardan oluşan bir dizi: [0 0 0 0 0 0 0 0 0 0]

5- 10 elemanlı birlerden oluşan bir dizi: [1 1 1 1 1 1 1 1 1 1]

6- (0-100) arasında eşit aralıklı 5 sayı: [  0.  25.  50.  75. 100.]

7- (10-30) arasında rastgele 5 tane tamsayı:[12 16 29 27 25]

8- [-1 ile 1] arasında 10 adet sayı: [-0.68351368 -0.59445796 -0.23020002 -0.83523487 -0.65849235  0.55418757
 -0.92280135  0.37976469  0.0633305  -0.14887727]

9- (3x5) boyutlarında (10-50) arasında rastgele bir matris:
 [[34 39 13 10 12]
 [23 31 37 42 44]
 [24 39 35 17 30]]

10- Matris'in sütun sayıları toplamı:[ 81 109  85  69  86]

10- Matris'in satır sayıları toplamı:[108 177 145]

11- Matrisin en büyük değeri: 44
11- Matrisin en küçük değeri: 10
11- Matrisin ortalama değ