# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
arrayNumpy = np.array([28, 97, 12, 397, 2])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
arraySorted= np.sort(arrayNumpy)
print(arraySorted)

[  2  12  28  97 397]


# Problem 2

In [19]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
arrayNumpy1=([10,15,30,45,60])
print(arrayNumpy1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arrayNumpy2 =np.arange (5,16)
print(arrayNumpy2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arrayNumpy3 = np.arange (50,101,5)
print(arrayNumpy3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
arrayNumpy4= np.full(10,0)
print(arrayNumpy4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
arrayNumpy5=np.full(10,1)
print(arrayNumpy5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arrayNumpy6= np.linspace(0,100,5)
print(arrayNumpy6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arrayNumpy7= np.random.randint(10,31,size=5)
print(arrayNumpy7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arrayNumpy8= np.random.uniform(-1,1,size=10)
print(arrayNumpy8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10, 15, 30, 45, 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[  0.  25.  50.  75. 100.]
[25 20 26 11 14]
[-0.99353678  0.60661458  0.34646942  0.6939316   0.55156883  0.25222813
  0.46356385 -0.52942451  0.99570043 -0.27052249]
